#!/usr/bin/env bash
# fast-iter-setup.sh — provision a single peer instance for fast bench-iter cycles.
#
# Use the CURRENT host as the DUT (DPDK NIC bind, etc. are operator-managed).
# Spin up ONE peer EC2 instance from the bench-pair AMI running:
#   - echo-server         on :10001   (bench-rtt + bench-tx-burst + bench-tx-maxtp dpdk/fstack arms)
#   - linux-tcp-sink      on :10002   (bench-tx-maxtp linux arm)
#   - burst-echo-server   on :10003   (bench-rx-burst)
#
# Round-trip: ~1-2 min provision, ~30 s teardown — vs. ~6.5h for the full
# scripts/bench-nightly.sh fleet+matrix run.
#
# Usage:
#   ./scripts/fast-iter-setup.sh up          # provision + start servers; writes .fast-iter.env
#   ./scripts/fast-iter-setup.sh down        # tear down peer + clear state
#   ./scripts/fast-iter-setup.sh info        # print peer state + reachability
#   ./scripts/fast-iter-setup.sh sh          # ssh into the peer (debug)
#
# After `up`:
#   source ./.fast-iter.env
#   sudo ./target/release/bench-rtt --stack dpdk_net --peer-ip "$PEER_IP" \
#       --peer-port 10001 --output-csv /tmp/quick-rtt.csv ...
#   ./scripts/fast-iter-setup.sh down
#
# State files:
#   $HOME/.bench-fast-iter.state.json   peer instance id + ip + port map
#   ./.fast-iter.env                    sourceable env (PEER_IP, PEER_SSH, *_PORT)
# Override via $BENCH_FAST_ITER_STATE / $BENCH_FAST_ITER_ENV.
#
# Env overrides (export before calling `up`):
#   PEER_AMI            AMI ID                   (default: ami-0e483926d07d19647 — bench-pair 1.0.15)
#   PEER_INSTANCE_TYPE  EC2 instance type        (default: c6a.xlarge)
#   PEER_SUBNET         VPC subnet ID            (default: subnet-05d4a1cf65e5df23c)
#   PEER_SG             security group ID        (default: sg-093d563579a51ca88)
#   AWS_PROFILE         AWS credentials profile  (default: resd-infra-operator)
#   AWS_REGION          AWS region               (default: ap-south-1)
#   SSH_KEY             local ssh privkey path   (default: $HOME/.ssh/id_ed25519)
#
# Why direct `aws ec2 run-instances` and not `resd-aws-infra setup bench-pair`?
#   `bench-pair` provisions the FULL fleet (DUT + peer) — that's the nightly
#   path. Fast-iter wants ONE peer; the current host is the DUT. Mirrors the
#   provisioning shape used by scripts/bench-quick.sh.
set -euo pipefail

mode="${1:-info}"

# ---------------------------------------------------------------------------
# Configuration (env-overridable).
# ---------------------------------------------------------------------------
PEER_AMI="${PEER_AMI:-ami-0e483926d07d19647}"
PEER_SUBNET="${PEER_SUBNET:-subnet-05d4a1cf65e5df23c}"
PEER_SG="${PEER_SG:-sg-093d563579a51ca88}"
PEER_INSTANCE_TYPE="${PEER_INSTANCE_TYPE:-c6a.xlarge}"
ECHO_PORT=10001
SINK_PORT=10002
BURST_PORT=10003

AWS_PROFILE="${AWS_PROFILE:-resd-infra-operator}"
AWS_REGION="${AWS_REGION:-ap-south-1}"
export AWS_PROFILE AWS_REGION

SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519}"
SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o ServerAliveInterval=30 -o ProxyCommand=none -i "$SSH_KEY")

STATE_FILE="${BENCH_FAST_ITER_STATE:-$HOME/.bench-fast-iter.state.json}"
WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${BENCH_FAST_ITER_ENV:-$WORKDIR/.fast-iter.env}"

# ---------------------------------------------------------------------------
# Helpers.
# ---------------------------------------------------------------------------
log() { printf '[fast-iter %s] %s\n' "$(date -u +%H:%M:%S)" "$*"; }
die() { printf '[fast-iter] ERROR: %s\n' "$*" >&2; exit 1; }

# Push the local SSH pubkey into EC2 Instance Connect's 60 s grant window.
push_ic_pubkey() {
    local instance_id="$1"
    aws ec2-instance-connect send-ssh-public-key \
        --instance-id "$instance_id" \
        --instance-os-user ubuntu \
        --ssh-public-key "file://${SSH_KEY}.pub" \
        --output text --query 'Success' >/dev/null
}

require_state() {
    [ -f "$STATE_FILE" ] || die "no state at $STATE_FILE — run '$0 up' first"
    PEER_INSTANCE_ID="$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['instance_id'])")"
    PEER_IP="$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['peer_ip'])")"
}

write_env_file() {
    local instance_id="$1"
    local peer_ip="$2"
    cat >"$ENV_FILE" <<EOF
# fast-iter env — generated by scripts/fast-iter-setup.sh on $(date -u +%FT%TZ)
# Source this file (\`source ./.fast-iter.env\`) before invoking bench tools.
export PEER_IP="$peer_ip"
export PEER_SSH="ubuntu@$peer_ip"
export PEER_INSTANCE_ID="$instance_id"
export PEER_ECHO_PORT="$ECHO_PORT"
export PEER_SINK_PORT="$SINK_PORT"
export PEER_BURST_PORT="$BURST_PORT"
EOF
}

# ---------------------------------------------------------------------------
# `up` — build peer binaries, launch one peer EC2, deploy + start servers.
#        Trap aborts mid-flight: terminate the half-provisioned instance so
#        the operator isn't left paying for a peer with no echo-server.
# ---------------------------------------------------------------------------
cmd_up() {
    if [ -f "$STATE_FILE" ]; then
        log "already up: state at $STATE_FILE — run '$0 down' first"
        cat "$STATE_FILE"
        exit 1
    fi

    cd "$WORKDIR"

    # Prereqs.
    local missing=0
    for bin in aws ssh scp python3 make; do
        if ! command -v "$bin" >/dev/null 2>&1; then
            log "MISSING prereq: $bin"
            missing=$((missing + 1))
        fi
    done
    [ "$missing" -eq 0 ] || die "$missing prereq(s) missing"
    [ -f "$SSH_KEY" ] || die "ssh key not found: $SSH_KEY"
    [ -f "${SSH_KEY}.pub" ] || die "ssh pubkey not found: ${SSH_KEY}.pub"
    aws sts get-caller-identity >/dev/null 2>&1 \
        || die "aws creds not configured (aws sts get-caller-identity failed; AWS_PROFILE=$AWS_PROFILE)"

    log "=== fast-iter up ==="
    log "  ami=$PEER_AMI type=$PEER_INSTANCE_TYPE region=$AWS_REGION"

    # [1/4] Build peer C binaries.
    log "[1/4] building peer C binaries (echo-server + burst-echo-server + linux-tcp-sink)"
    make -C tools/bench-e2e/peer echo-server >/dev/null
    make -C tools/bench-e2e/peer burst-echo-server >/dev/null
    make -C tools/bench-vs-linux/peer linux-tcp-sink >/dev/null
    for f in tools/bench-e2e/peer/echo-server \
             tools/bench-e2e/peer/burst-echo-server \
             tools/bench-vs-linux/peer/linux-tcp-sink; do
        [ -f "$f" ] || die "expected build artifact missing: $f"
    done

    # [2/4] Launch peer.
    log "[2/4] launching peer EC2 instance"
    local launch_json instance_id
    launch_json="$(aws ec2 run-instances \
        --image-id "$PEER_AMI" \
        --instance-type "$PEER_INSTANCE_TYPE" \
        --subnet-id "$PEER_SUBNET" \
        --security-group-ids "$PEER_SG" \
        --no-associate-public-ip-address \
        --count 1 \
        --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=fast-iter-peer}]" \
        --output json)"
    instance_id="$(python3 -c "import sys,json; print(json.load(sys.stdin)['Instances'][0]['InstanceId'])" <<<"$launch_json")"
    log "  instance_id=$instance_id"

    # Trap: if anything below this point fails, terminate the instance so the
    # operator doesn't bleed money on a half-provisioned peer.
    cleanup_on_failure() {
        local rc=$?
        if [ $rc -ne 0 ]; then
            log "FAILED rc=$rc — terminating $instance_id to avoid orphan"
            aws ec2 terminate-instances --instance-ids "$instance_id" --output text >/dev/null 2>&1 || true
            rm -f "$STATE_FILE" "$ENV_FILE"
        fi
    }
    trap cleanup_on_failure EXIT

    aws ec2 wait instance-running --instance-ids "$instance_id"
    local peer_ip
    peer_ip="$(aws ec2 describe-instances --instance-ids "$instance_id" \
        --query 'Reservations[0].Instances[0].PrivateIpAddress' --output text)"
    log "  peer_ip=$peer_ip"

    # [3/4] Wait for SSH, prepare data NIC, deploy binaries.
    log "[3/4] waiting for sshd on $peer_ip (push pubkey via EC2 Instance Connect)"
    local retries=0
    until push_ic_pubkey "$instance_id" && \
          ssh "${SSH_OPTS[@]}" -o ConnectTimeout=5 -o BatchMode=yes "ubuntu@$peer_ip" true 2>/dev/null; do
        retries=$((retries + 1))
        if [ "$retries" -ge 72 ]; then
            die "ssh timeout after 6 min — check SG ingress + EC2 Instance Connect IAM"
        fi
        if [ $((retries % 6)) -eq 0 ]; then
            log "  still waiting ... ($((retries * 5))s elapsed)"
        fi
        sleep 5
    done
    log "  sshd ready"

    # AMI boots the data NIC bound to vfio-pci (DUT-style). For the peer we
    # need it bound to the kernel ena driver so the userspace echo-server /
    # linux-tcp-sink / burst-echo-server can listen on a kernel TCP socket.
    log "  preparing peer data NIC + firewall"
    push_ic_pubkey "$instance_id"
    ssh "${SSH_OPTS[@]}" "ubuntu@$peer_ip" 'sudo bash -s' <<'REMOTE_EOF'
set -eu
PCI=$(/usr/local/bin/dpdk-devbind.py --status-dev net 2>/dev/null | awk '/drv=vfio-pci/ {print $1; exit}' || true)
if [ -n "$PCI" ]; then
    echo "peer-prep: rebinding $PCI vfio-pci -> ena"
    /usr/local/bin/dpdk-devbind.py --bind ena "$PCI"
    sleep 1
else
    echo "peer-prep: no vfio-pci NIC (already ena)"
fi
# Drop firewall on all interfaces so DUT can reach the three echo-server ports.
iptables -I INPUT -j ACCEPT 2>/dev/null || true
echo "peer-prep: done"
REMOTE_EOF

    log "  scp peer binaries"
    push_ic_pubkey "$instance_id"
    scp "${SSH_OPTS[@]}" \
        tools/bench-e2e/peer/echo-server \
        tools/bench-e2e/peer/burst-echo-server \
        tools/bench-vs-linux/peer/linux-tcp-sink \
        "ubuntu@${peer_ip}:/tmp/"

    # [4/4] Start the three peer servers (mirrors bench-nightly step [6/12]).
    log "[4/4] starting peer servers"
    push_ic_pubkey "$instance_id"
    # shellcheck disable=SC2029  # ECHO_PORT/SINK_PORT/BURST_PORT are script-local constants;
    # client-side expansion is intentional so the remote shell sees concrete port literals.
    ssh "${SSH_OPTS[@]}" "ubuntu@$peer_ip" "
        set -eu
        chmod +x /tmp/echo-server /tmp/burst-echo-server /tmp/linux-tcp-sink
        nohup /tmp/echo-server $ECHO_PORT >/tmp/echo-server.log 2>&1 </dev/null &
        nohup /tmp/linux-tcp-sink $SINK_PORT >/tmp/linux-tcp-sink.log 2>&1 </dev/null &
        nohup /tmp/burst-echo-server $BURST_PORT >/tmp/burst-echo-server.log 2>&1 </dev/null &
        sleep 1
        pgrep -a echo-server || echo 'WARN echo-server not running'
        pgrep -a linux-tcp-sink || echo 'WARN linux-tcp-sink not running'
        pgrep -a burst-echo-server || echo 'WARN burst-echo-server not running'
    "

    # Persist state + env file.
    python3 -c "
import json
json.dump({
    'instance_id': '$instance_id',
    'peer_ip': '$peer_ip',
    'echo_port': $ECHO_PORT,
    'sink_port': $SINK_PORT,
    'burst_port': $BURST_PORT,
    'created_utc': '$(date -u +%FT%TZ)',
}, open('$STATE_FILE', 'w'), indent=2)
"
    write_env_file "$instance_id" "$peer_ip"

    # Success — drop the failure trap so a clean exit doesn't terminate
    # the peer we just provisioned.
    trap - EXIT

    log "=== fast-iter up complete ==="
    log "  state    -> $STATE_FILE"
    log "  env file -> $ENV_FILE"
    log "  PEER_IP=$peer_ip"
    log "  Ports: echo=$ECHO_PORT sink=$SINK_PORT burst=$BURST_PORT"
    log "  Next:  source $ENV_FILE && sudo ./target/release/bench-rtt --peer-ip \"\$PEER_IP\" ..."
    log "  Done:  $0 down"
}

# ---------------------------------------------------------------------------
# `down` — terminate peer + clear state.
# ---------------------------------------------------------------------------
cmd_down() {
    if [ ! -f "$STATE_FILE" ]; then
        log "no state at $STATE_FILE — nothing to tear down"
        rm -f "$ENV_FILE"
        exit 0
    fi
    require_state
    log "=== fast-iter down ==="
    log "  terminating $PEER_INSTANCE_ID (peer_ip=$PEER_IP)"
    aws ec2 terminate-instances --instance-ids "$PEER_INSTANCE_ID" --output text >/dev/null
    rm -f "$STATE_FILE" "$ENV_FILE"
    log "  state cleared"
}

# ---------------------------------------------------------------------------
# `info` — print state + reachability check.
# ---------------------------------------------------------------------------
cmd_info() {
    if [ ! -f "$STATE_FILE" ]; then
        log "not provisioned (no state at $STATE_FILE)"
        exit 0
    fi
    require_state
    log "=== fast-iter info ==="
    log "  state file: $STATE_FILE"
    log "  env file:   $ENV_FILE"
    log "  peer_ip:    $PEER_IP"
    log "  instance:   $PEER_INSTANCE_ID"
    log "  ports:      echo=$ECHO_PORT sink=$SINK_PORT burst=$BURST_PORT"
    local state
    state="$(aws ec2 describe-instances --instance-ids "$PEER_INSTANCE_ID" \
        --query 'Reservations[0].Instances[0].State.Name' --output text 2>/dev/null || echo "unknown")"
    log "  ec2 state:  $state"
    if [ "$state" = "running" ]; then
        push_ic_pubkey "$PEER_INSTANCE_ID" 2>/dev/null || log "  WARN ec2-instance-connect push failed"
        if ssh "${SSH_OPTS[@]}" -o ConnectTimeout=5 -o BatchMode=yes "ubuntu@$PEER_IP" \
                "pgrep -a echo-server >/dev/null && pgrep -a linux-tcp-sink >/dev/null && pgrep -a burst-echo-server >/dev/null" 2>/dev/null; then
            log "  servers:    all three running"
        else
            log "  servers:    NOT all running (or ssh unreachable) — try '$0 sh'"
        fi
    fi
}

# ---------------------------------------------------------------------------
# `sh` — ssh into the peer.
# ---------------------------------------------------------------------------
cmd_sh() {
    require_state
    push_ic_pubkey "$PEER_INSTANCE_ID"
    log "ssh ubuntu@$PEER_IP"
    exec ssh "${SSH_OPTS[@]}" "ubuntu@$PEER_IP"
}

# ---------------------------------------------------------------------------
# Dispatch.
# ---------------------------------------------------------------------------
case "$mode" in
    up)   cmd_up ;;
    down) cmd_down ;;
    info) cmd_info ;;
    sh)   cmd_sh ;;
    -h|--help|help)
        sed -n '2,40p' "$0"
        exit 0
        ;;
    *)
        echo "fast-iter: unknown mode '$mode'; expected up|down|info|sh" >&2
        exit 2
        ;;
esac
