#![no_main]
//! A9 Task 20 — libFuzzer **persistent-mode** target for the full
//! `Engine::inject_rx_frame` → `dispatch_one_rx_mbuf` → L2/L3/TCP
//! pipeline (spec D3, T1.5). Complements the pure-module coverage
//! targets (`header_parser`, `tcp_options`, `tcp_sack`, `tcp_seq`,
//! `tcp_state_fsm`, `tcp_reassembly`) by driving a **real** DPDK-backed
//! engine end-to-end with arbitrary bytes.
//!
//! # Persistent-mode layout
//!
//! libFuzzer invokes `fuzz_target!` once per test input. Building a new
//! Engine per iteration would cost ~10 ms (EAL port init + mempool
//! allocation + TAP device configure) — unacceptable for libFuzzer's
//! expected ≥10⁴ iters/sec. We therefore construct a single `Engine`
//! on the *first* call via [`OnceLock::get_or_init`] and reuse it for
//! the remainder of the fuzz job. Every iteration only pays the
//! `inject_rx_frame` body (mbuf alloc + copy + dispatch — ~µs).
//!
//! # Env gating
//!
//! Engine construction piggybacks on
//! [`dpdk_net_core::test_fixtures::make_test_engine`]. The fixture
//! requires `DPDK_NET_TEST_TAP=1` + hugepages + sudo (same gate the
//! A9 integration tests use). When the gate is unmet the fixture
//! returns `None`; we cache that `None` and the `fuzz_target!` body
//! degrades to a no-op so the target compiles and runs everywhere.
//! In that mode libFuzzer still drives millions of iters — proves
//! the target is sound — but exercises no coverage. Set
//! `DPDK_NET_TEST_TAP=1` (under sudo, with hugepages mounted) to
//! get real end-to-end `tcp_input` coverage.
//!
//! # Invariants checked
//!
//! After every `inject_rx_frame` call we walk the engine's flow
//! table and assert, for every live connection:
//!
//!   I1. `snd_una` is not ahead of `snd_nxt` in wrap-safe order.
//!       Violating this means the stack acked bytes we never sent —
//!       a fatal data-loss invariant. Skips connections in states
//!       where the fields are not yet well-defined (`Closed` / `Listen`).
//!
//!   I2. The connection's four-tuple round-trips through
//!       [`FlowTable::lookup_by_tuple`]. An inbound segment corrupting
//!       the hash-by-tuple index would surface here.
//!
//! libFuzzer detects outright panics / sanitizer failures
//! automatically; the explicit asserts above catch *silent* state
//! corruption that doesn't crash on its own.

use libfuzzer_sys::fuzz_target;
use std::sync::OnceLock;

use dpdk_net_core::engine::Engine;
use dpdk_net_core::tcp_seq::seq_le;
use dpdk_net_core::tcp_state::TcpState;

// `Engine` is `!Send + !Sync` because it holds several `RefCell`s and
// raw DPDK pointers on the single-lcore hot path. libFuzzer drives
// `fuzz_target!` on a single thread for the lifetime of the job, so
// sharing the cached engine across (non-existent) threads never
// happens in practice. A thin newtype with unsafe `Send + Sync` impls
// is the cheapest way to unlock `OnceLock<T>`'s `T: Send + Sync`
// bounds without paying a `Mutex` per iteration (the mutex would
// dwarf the sub-µs dispatch cost).
struct EngineCell(Option<Engine>);

// SAFETY: libFuzzer is single-threaded per fuzz job. The `OnceLock`
// below writes exactly once (first iteration) and every subsequent
// read returns a `&EngineCell` on that same thread. No concurrent
// access or cross-thread send ever materializes, so the `Send +
// Sync` assertions are vacuous.
unsafe impl Sync for EngineCell {}
unsafe impl Send for EngineCell {}

static ENGINE: OnceLock<EngineCell> = OnceLock::new();

fn get_engine() -> Option<&'static Engine> {
    ENGINE
        .get_or_init(|| EngineCell(dpdk_net_core::test_fixtures::make_test_engine()))
        .0
        .as_ref()
}

fuzz_target!(|data: &[u8]| {
    // First-iter: try to stand up a real DPDK engine. Without
    // `DPDK_NET_TEST_TAP=1` + hugepages + sudo this returns `None`
    // and every subsequent iteration is a zero-cost return — the
    // target is a compile-verified placeholder in that environment.
    let Some(engine) = get_engine() else { return; };

    // Drive the fuzzer-generated bytes through the engine's synthetic
    // RX hook. `inject_rx_frame` returns typed errors for
    // mempool-exhaustion / frame-too-large — those are not bugs
    // (libFuzzer happily generates 128 KiB inputs the mempool can't
    // hold), so we discard the Result. A panic here *is* a bug:
    // libFuzzer will save the input and report a crash.
    let _ = engine.inject_rx_frame(data);

    // After dispatch, walk every live connection and assert
    // structural invariants. `iter_handles` is a slow-path iterator
    // over occupied slots — acceptable on the fuzz cadence.
    let ft = engine.flow_table();
    for handle in ft.iter_handles().collect::<Vec<_>>() {
        let Some(conn) = ft.get(handle) else { continue; };

        // I1: snd_una must not lead snd_nxt in wrap-safe order.
        // The fields carry their production values only once the
        // connection has exchanged SYNs; before that they're
        // zero-initialised and the invariant trivially holds.
        if !matches!(conn.state, TcpState::Closed | TcpState::Listen) {
            assert!(
                seq_le(conn.snd_una, conn.snd_nxt),
                "flow_table corruption: conn state={:?} snd_una={} ahead of snd_nxt={}",
                conn.state,
                conn.snd_una,
                conn.snd_nxt,
            );
        }

        // I2: by-tuple index must round-trip. A mismatch here would
        // mean inject_rx_frame corrupted the `HashMap<FourTuple, _>`
        // backing — silent state bug the fuzzer would otherwise miss.
        let tuple = conn.four_tuple();
        let looked_up = ft.lookup_by_tuple(&tuple);
        assert_eq!(
            looked_up,
            Some(handle),
            "flow_table by-tuple index broken: tuple={:?} expected={} got={:?}",
            tuple,
            handle,
            looked_up,
        );
    }
});
